apiVersion: v1
kind: Service
metadata:
  name: product-categories-service
spec:
  selector:
    app: product-categories
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: grpc
      port: 5001
      targetPort: 5001
