apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server:
      name: kibana
      host: "0.0.0.0"
    elasticsearch:
      hosts: ["http://elasticsearch-service:9200"]
