apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      protocol: TCP
      nodePort: 30601
  selector:
    app: kibana