apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'auth-service-rest'
        static_configs:
          - targets: ['auth-service:6000']
      - job_name: 'product-catalog-service-rest'
        static_configs:
          - targets: ['product-catalog-service:7000']
      - job_name: 'product-category-service-rest'
        static_configs:
          - targets: ['product-categories-service:5000']