apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-deployment
  labels:
    app: product-catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog-service
          image: localhost:32000/product-catalog-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: default-secret
          resources:
            limits:
              cpu: "0.2"
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 7000
              name: http
            - containerPort: 7001
              name: grpc
      restartPolicy: Always
