apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  selector:
    app: product-catalog
  ports:
    - name: http
      port: 7000
      targetPort: 7000
    - name: grpc
      port: 7001
      targetPort: 7001
