global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service-rest'
    static_configs:
      - targets: ['localhost:6000']
  - job_name: 'product-catalog-service-rest'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'product-category-service-rest'
    static_configs:
      - targets: ['localhost:5000']
