// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: category.proto

package category

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CreateCategoryRequest) Validate() error {
	return nil
}
func (this *CreateCategoryResponse) Validate() error {
	if this.Result != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Result); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
		}
	}
	return nil
}
func (this *SearchField) Validate() error {
	return nil
}
func (this *SearchRequest) Validate() error {
	for _, item := range this.SearchFields {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("SearchFields", err)
			}
		}
	}
	return nil
}
func (this *CategoryDto) Validate() error {
	return nil
}
func (this *SearchCategoryResponse) Validate() error {
	for _, item := range this.CategoryDtoList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CategoryDtoList", err)
			}
		}
	}
	if this.Result != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Result); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
		}
	}
	return nil
}
func (this *Result) Validate() error {
	return nil
}
