// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CreateProductRequest) Validate() error {
	if !(this.Price > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Price", fmt.Errorf(`value '%v' must be strictly greater than '0'`, this.Price))
	}
	return nil
}
func (this *CreateProductResponse) Validate() error {
	if this.Result != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Result); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
		}
	}
	return nil
}
func (this *SearchField) Validate() error {
	return nil
}
func (this *SearchRequest) Validate() error {
	for _, item := range this.SearchFields {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("SearchFields", err)
			}
		}
	}
	return nil
}
func (this *Product) Validate() error {
	if this.Category != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Category); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Category", err)
		}
	}
	return nil
}
func (this *Category) Validate() error {
	return nil
}
func (this *SearchProductResponse) Validate() error {
	for _, item := range this.ProductList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ProductList", err)
			}
		}
	}
	if this.Result != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Result); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
		}
	}
	return nil
}
func (this *GetProductByIdRequest) Validate() error {
	return nil
}
func (this *GetProductByIdResponse) Validate() error {
	if this.Product != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Product); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Product", err)
		}
	}
	if this.Result != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Result); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
		}
	}
	return nil
}
func (this *Result) Validate() error {
	return nil
}
