apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  type: ClusterIP
  ports:
    - port: 5044
      targetPort: 5044
      protocol: TCP
      name: logstash
  selector:
    app: logstash
